name: udevs_video_player
description: Play video natively and easily
version: 0.0.2
homepage: https://github.com/MobileUdevs/udevs_video_player.git

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: uz.udevs.udevs_video_player
        pluginClass: UdevsVideoPlayerPlugin
      ios:
        pluginClass: UdevsVideoPlayerPlugin